/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{vue,js,ts,jsx,tsx}',
    // This will allow consuming projects to scan this package's components
    './node_modules/@twymai/vue-twymx/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Custom colors used in the components
        indigo: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'Noto Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
  // Safelist important classes used in the components to prevent purging
  safelist: [
    'bg-gray-100',
    'bg-white',
    'bg-indigo-600',
    'bg-indigo-700',
    'hover:bg-indigo-700',
    'hover:bg-gray-50',
    'text-gray-900',
    'text-gray-700',
    'text-gray-600',
    'text-gray-500',
    'text-white',
    'text-red-600',
    'text-red-500',
    'text-indigo-600',
    'text-indigo-500',
    'border-gray-300',
    'border-transparent',
    'focus:ring-indigo-500',
    'focus:border-indigo-500',
    'focus:ring-2',
    'focus:ring-offset-2',
    'disabled:opacity-50',
    'rounded-md',
    'rounded-lg',
    'shadow-sm',
    'shadow-md',
    'space-y-4',
    'space-y-6',
    'min-h-screen',
    'max-w-md',
    'w-full',
    'h-6',
    'w-6',
    'h-5',
    'w-5',
    'absolute',
    'relative',
    'top-6',
    'left-6',
    'flex',
    'items-center',
    'justify-center',
    'justify-between',
    'block',
    'mt-1',
    'mt-2',
    'mt-6',
    'mt-8',
    'mr-2',
    'px-2',
    'px-3',
    'px-4',
    'py-2',
    'py-2.5',
    'p-8',
    'text-sm',
    'text-2xl',
    'font-bold',
    'font-medium',
    'text-center',
    'hover:text-gray-800',
    'hover:text-indigo-500',
    'focus:outline-none',
    'appearance-none',
    'cursor-not-allowed',
    'gap-2',
    'sm:text-sm',
    'placeholder-gray-400',
    'border'
  ]
}
