/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: 'twymx-',
  content: [
    './src/**/*.{vue,js,ts,jsx,tsx}',
    // This will allow consuming projects to scan this package's components
    './node_modules/@twymai/vue-twymx/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Custom colors used in the components
        indigo: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'Noto Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
  // Safelist important classes used in the components to prevent purging
  safelist: [
    'twymx-bg-gray-100',
    'twymx-bg-white',
    'twymx-bg-indigo-600',
    'twymx-bg-indigo-700',
    'hover:twymx-bg-indigo-700',
    'hover:twymx-bg-gray-50',
    'twymx-text-gray-900',
    'twymx-text-gray-700',
    'twymx-text-gray-600',
    'twymx-text-gray-500',
    'twymx-text-white',
    'twymx-text-red-600',
    'twymx-text-red-500',
    'twymx-text-indigo-600',
    'twymx-text-indigo-500',
    'twymx-border-gray-300',
    'twymx-border-transparent',
    'focus:twymx-ring-indigo-500',
    'focus:twymx-border-indigo-500',
    'focus:twymx-ring-2',
    'focus:twymx-ring-offset-2',
    'disabled:twymx-opacity-50',
    'twymx-rounded-md',
    'twymx-rounded-lg',
    'twymx-shadow-sm',
    'twymx-shadow-md',
    'twymx-space-y-4',
    'twymx-space-y-6',
    'twymx-min-h-screen',
    'twymx-max-w-md',
    'twymx-w-full',
    'twymx-h-6',
    'twymx-w-6',
    'twymx-absolute',
    'twymx-relative',
    'twymx-top-6',
    'twymx-left-6',
    'twymx-flex',
    'twymx-items-center',
    'twymx-justify-center',
    'twymx-block',
    'twymx-mt-1',
    'twymx-mt-2',
    'twymx-mt-6',
    'twymx-mt-8',
    'twymx-px-3',
    'twymx-px-4',
    'twymx-py-2',
    'twymx-py-2.5',
    'twymx-p-8',
    'twymx-text-sm',
    'twymx-text-2xl',
    'twymx-font-bold',
    'twymx-font-medium',
    'twymx-text-center',
    'hover:twymx-text-gray-800',
    'hover:twymx-text-indigo-500',
    'focus:twymx-outline-none',
    'twymx-appearance-none',
    'twymx-cursor-not-allowed',
    'twymx-gap-2',
    'twymx-justify-between',
    'sm:twymx-text-sm',
    'twymx-placeholder-gray-400'
  ]
}
